### ISSUE TITLE
Can you show the proof of it having Token logger?

### ISSUE THREAD

**Issue by ghost** [ToxicedIsOnTheLand/RebelClient#2]

**Comment by ToxicedIsOnTheLand** [comment]
i did not accuse the client of having a token logger nor a ip logger

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/88583135/154825752-a0a3505d-24d5-4a94-91d9-4c1d77b68a9f.png)
lol cope

**Comment by ToxicedIsOnTheLand** [comment]
![image](https://user-images.githubusercontent.com/94137529/154832533-668937d8-64c5-4f79-bc1c-b1340eebdc9c.png)

**Comment by ghost** [comment]
What do you mean by this screenshot lol

**Comment by ToxicedIsOnTheLand** [comment]
> What do you mean by this screenshot lol

mrolp accused it
